### ISSUE TITLE
SSR with api data

### ISSUE THREAD

**Issue by OlgaPolunina** [StopNGo/react-proto#3]
Please help me how to initialize the preloadState correctly for SSR to work with api

serverRenderer.tsx
```
let preloadState: Partial<RootState> = { counter: { value: 42 } };
const store = initStore(preloadState);
const { dispatch } = store;
await Promise.all(dispatch(pokemonApi.util.getRunningQueriesThunk()))
preloadState = {...preloadState, ...store.getState()}
```

**Comment by StopNGo** [comment]
Hello!
I'm just start working at a release that includes SSR API request, so my answer for a moment could be not complete, because I am not sure that I know all the pitfalls that could be faced.
Did you get respond from the API request successfully? You should use  buildCreateApi() with some flags (https://redux-toolkit.js.org/rtk-query/usage/server-side-rendering#server-side-rendering-elsewhere).

Because I do not see any issues in the passing the preloaded state.

**Comment by OlgaPolunina** [comment]
Yes, api is called with ssr, but I can’t initialize the state, I’m doing something wrong or at the wrong moment.
Yes, of course, I read https://redux-toolkit.js.org/rtk-query/usage/server-side-rendering#server-side-rendering-elsewhere
And changed my buildCreateApi
If you manage to set it up and show it, I would be very grateful.
Thank you for such a great template.

**Comment by StopNGo** [comment]
Sorry, due blackouts in my country, I can not pay a lot of attention to this project.

Did you solve the issue?

If not:
- Could you show me a full code of this part of the server (with API request and preloadState forming);
- Have you checked the the preloadState in the server response, it should be in the window.__PRELOADED_STATE__ variable in the HTML header.

Thanks!

**Comment by StopNGo** [comment]
Hi! You can now check the latest release to see how to do API requests on server side and initialize the preloaded state correctly for SSR.
Bee free to ask me any other questions.
Thanks!
